name: Build and Push Docker Image

on:
  push:
    branches:
      - '**'

jobs:
  build-and-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Docker Build Push
        uses: ./.github/actions/docker-build-push
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_pat: ${{ secrets.DOCKER_PAT }}
          context: .
          file: cli.Dockerfile
          platforms: linux/amd64,linux/arm64
          build_tags: |
            rivetgg/opengb:${{ github.sha }}
            rivetgg/opengb:${{ github.ref_name || '' }}
