name: Build and Push Docker Image

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build-and-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build And Push with SHA
        if: github.ref_type == 'branch'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: cli.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/rivet-gg/opengb:${{ github.sha }}

      - name: Build And Push with Tag
        if: github.ref_type == 'tag'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: cli.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/rivet-gg/opengb:${{ github.sha }}
            ghcr.io/rivet-gg/opengb:${{ github.ref_name }}

      - name: Image Digest
        run: |
          echo "Image digest (amd64): ${{ steps.build-push.outputs.digest-amd64 }}"
          echo "Image digest (arm64): ${{ steps.build-push.outputs.digest-arm64 }}"

