name: Test all modules E2E
on:
  - push

env:
  CURRENT_WORKING_ENGINE_COMMIT: 3aab9bc2abcb8105fc3af837900ce4f7a932ad17

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      # Checkout registry repo
      - name: Checkout registry Repo
        uses: actions/checkout@v4

      # Install Deno to run OpenGB
      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.41.1"

      # Install OpenGB
      - name: Install OpenGB
        run: deno install --name opengb --force --allow-net --allow-read --allow-env --allow-run --allow-write --allow-sys https://raw.githubusercontent.com/rivet-gg/opengb/main/src/cli/main.ts

      # Run tests on all modules in the registry
      - name: Run Tests for all modules
        env:
          VERBOSE: true
        run: cd tests/basic/ && opengb test --strict-schemas --force-deploy-migrations || docker ps

      # Inspect containers running after tests finish
      - name: docker ps
        if: always()
        run: docker ps
